post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '3.0'
end
end
end
source 'https:www.github.com/CocoaPods/Specs.git'
platform:ios,'8.0'
target 'TuBu' do
use_frameworks!

pod 'SDCycleScrollView'
pod 'Alamofire', '~> 4.4.0'
pod 'SnapKit', '~> 3.2.0'
#pod 'YYKit'
pod 'SDWebImage'
pod 'SwiftyJSON', '~> 3.1.4'
end
